### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by Anonymous6598** [lorenzolpandolfo/pytext#1]
- Hello @lorenzolpandolfo,

This is @Anonymous6598 - junior python desktop developer. I saw your project and I wanted to say that your project is really interesting. I would suggest you an offer - you subscribe to me and you get access to My_Diary - python based text/code editor. In my project you'll be able to see, how to use aspose.words api and docx module. So what do you think?

- Anonymos6598

**Comment by lorenzolpandolfo** [comment]
Hello, @Anonymous6598 !
Thank you for the interest in my project and for your offer, but I can't afford any monetary amount in this moment :(
Nonetheless, you have a lot of cool projects and I think we could learn a lot from each other!

**Comment by Anonymous6598** [comment]
I don't need money, just follow me. That's it.

**Comment by Anonymous6598** [comment]
> Hello, @Anonymous6598 !
> Thank you for the interest in my project and for your offer, but I can't afford any monetary amount in this moment :(
> Nonetheless, you have a lot of cool projects and I think we could learn a lot from each other!

I don't need money, just follow me. That's it.

**Comment by Anonymous6598** [comment]
Just be my follower

**Comment by lorenzolpandolfo** [comment]
Oh, ok! Sorry for that! 🤭

**Comment by Anonymous6598** [comment]
> Oh, ok! Sorry for that! 🤭

It's ok
