### ISSUE TITLE
AI suggestion

### ISSUE THREAD

**Issue by Anonymous6598** [lorenzolpandolfo/pytext#13]
Hi @lorenzolpandolfo!
I have recently come up with an idea of integrating AI in your project. I have already integrated in my project - my diary. What do you think of this idea?
@Anonymous6598

**Comment by lorenzolpandolfo** [comment]
Hello @Anonymous6598 !
Using AI is a interesting idea, but now im focusing in simple but good implementations, like syntax highlight, autocomplete, multiple tabs, etc.
I never worked with AI before and it can be useful in many ways, but in moment I don't think it is the correct moment to add such feature. By now, I want to create a good base project with a limited scope, so we can launch pytext first release.
You added AI to your project and that's very interesting, but, in a objective way, what it can do? I'm curious!
Best wishes!

**Comment by Anonymous6598** [comment]
Hi @lorenzolpandolfo. Well, we can make code editor with replit ai - ai for coding. Therefore developers will like your project even more.

**Comment by Anonymous6598** [comment]
But I get your point.

**Comment by Anonymous6598** [comment]
> Hello @Anonymous6598 !
> Using AI is a interesting idea, but now im focusing in simple but good implementations, like syntax highlight, autocomplete, multiple tabs, etc.
> I never worked with AI before and it can be useful in many ways, but now I don't think it is the correct moment to add such feature. By now, I want to create a good base project with a limited scope, so we can launch pytext first release.
> You added AI to your project and that's very interesting, but, in a objective way, what it can do? I'm curious!
> Best wishes!
> 
> 
> 

In my project I integrated GenAI. In other words - just chatgpt inside of mine app.

**Comment by Anonymous6598** [comment]
I just added generative ai in my diary. That's it.

**Comment by lorenzolpandolfo** [comment]
> Hi @lorenzolpandolfo. Well, we can make code editor with replit ai - ai for coding. Therefore developers will like your project even more. 

and there is a way we can implement the replit ai to pytext?

**Comment by lorenzolpandolfo** [comment]
> I just added generative ai in my diary. That's it.

thats cool! you used pytorch or something?

**Comment by Anonymous6598** [comment]
> > Hi @lorenzolpandolfo. Well, we can make code editor with replit ai - ai for coding. Therefore developers will like your project even more. 
> 
> and there is a way we can implement the replit ai to pytext?

Yes

**Comment by Anonymous6598** [comment]
> > I just added generative ai in my diary. That's it.
> 
> thats cool! you used pytorch or something?

I used gpt4free API for it.

**Comment by Anonymous6598** [comment]
Just add

```Python
import g4f.local
```

**Comment by Anonymous6598** [comment]
And then make local client, and make a response, using replit ai model.
