### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by Anonymous6598** [lorenzolpandolfo/pytext#2]
Hello @lorenzolpandolfo!

I wanted to ask for permission to fork to pytext. Therefore I will be able to add Drag-And-Drop support to your app. So, what do you think?

@Anonymous6598

**Comment by lorenzolpandolfo** [comment]
Hey @Anonymous6598 !
Sure, no problem! Feel free to fork it. :)

**Comment by Anonymous6598** [comment]
Great! Thanks!

**Comment by lorenzolpandolfo** [comment]
@Anonymous6598 
In Pytext, a lot of code comments are in brazilian portuguese, so I will translate them to english to people that doesn't speak pt-br can understand the code better!
Also, some functions have non-intuitive names. I will change that too. :)

**Comment by Anonymous6598** [comment]
And by the way, where is `root` situated? It is necessary, because I have to change CTk class, therefore it will be possible to implement dnd.

**Comment by lorenzolpandolfo** [comment]
root is situated in the main.py
```
if __name__ == "__main__":
    root = ctk.CTk()
    app = MainApp(root)
    root.mainloop()
```
