### ISSUE TITLE
Congratulations letter.

### ISSUE THREAD

**Issue by Anonymous6598** [lorenzolpandolfo/pytext#4]
Hello @lorenzolpandolfo!
Congratulations on your project!!🎉🎉🎉🎉 Wish you luck.
@Anonymous6598

**Comment by lorenzolpandolfo** [comment]
Hello @Anonymous6598!
Thank you for your letter! Don't forget that you're a part of Pytext too. 😄
All the best to you! ❤️💯

**Comment by Anonymous6598** [comment]
I'm happy because you are happy!
