### ISSUE TITLE
Cooperation 

### ISSUE THREAD

**Issue by Anonymous6598** [lorenzolpandolfo/pytext#6]
Hello @lorenzolpandolfo!
How are you? I need help writing method for syntax highlight for My_Diary app. You can fork to it. Can you help me?
@Anonymous6598.

**Comment by Anonymous6598** [comment]
thanks for suggestion

**Comment by Anonymous6598** [comment]
but can you help me implement this method?

**Comment by lorenzolpandolfo** [comment]
I'm short on time, but when it is possible to me, I can help you, no problem!

**Comment by Anonymous6598** [comment]
Thank you

**Comment by Anonymous6598** [comment]
When you are ready to start, make an issue that you are ready to start in My_Diary repo and also fork to it.

**Comment by Anonymous6598** [comment]
> Hello @Anonymous6598 , how are you? Hope you're doing great. About syntax highlight, in the old version of pytext (main branch) I used a regex system, but I don't recommend you to do it this way. There is a python library named by "Pygments", that have a lexer with a lot of languages and it auto highlight it to you, but you need to parse the highlight result to Tkinter or Customtkinter text widget. I found this text editor, Chlorophyll, that have a syntax highlight using the Pygments lib. You can check how they did the syntax higlight in the source code: https://github.com/rdbende/chlorophyll Pytext is under a total refactor in its unstable branch and i will add syntax highlight the way chlorophyll did it too.

Thanks, i'm doing great. Preparing for uni exams.
